---
title: "Brennan Final Project"
author: "Leah Brennan"
date: "11/3/2019"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE, paged.print=TRUE)
```

## Load Packages

```{r}

#install.packages('tidyverse')
#install.packages('janitor')
#install.packages('tidycensus')
#install.packages('arcos')


library(tidyverse)
library(janitor)
library(tidycensus)
library(arcos)

# store an API key as an object called key
census_api_key("ee9c9f508567df0be614b71a5c58ebbb21cd991b")
key <- "uO4EK6I"

# Looking up variables:
acs_variables <- load_variables(2017, "acs5" )

county_geodata <- get_acs(geography = "county",
              variables = "B19013_001")
state_geodata <- get_acs(geography = "state",
              variables = "B01001_001", geometry = TRUE)

arcos_county_population_per_year <- county_population(key = key) %>%
  clean_names()

arcos_county_pills_per_year <- summarized_county_annual(key = key) %>%
  clean_names()

```

```{r}


# Make a dataframe that includes dosage unit information per census tract per year for Baltimore County, along with income per tract per year.

balco_tract_income <- get_acs(geography = "tract", state="MD", county="Baltimore County", variables = "B19019_001", geometry = TRUE)

balco_tract <- pharm_tracts(county = "Baltimore", state = "MD", key = key)

balco_annual_buyer <- combined_buyer_annual(county = "Baltimore", state = "MD", key = key)

balco_tract_data_working <- inner_join(balco_annual_buyer, balco_tract, by="BUYER_DEA_NO")

balco_tract_data_working <- inner_join(balco_tract_data_working, balco_tract_income, by =c("GEOID"))

balco_tract_data_working <- clean_names(balco_tract_data_working)


```

```{r}

# Remove unecessary columns.

balco_tract_data_working <-
  subset(balco_tract_data_working, select = c(buyer_dea_no, buyer_county_x, buyer_state_x, year, dosage_unit, affgeoid, geoid, tractce, name_x, lsad, variable, estimate, moe, geometry))


```

```{r}

# Make a dataframe that includes dosage unit information per census tract per year for Baltimore City, along with income per tract per year.


balcity_tract_income <- get_acs(geography = "tract", state="MD", county="Baltimore City", variables = "B19019_001", geometry = TRUE)

balcity_tract <- pharm_tracts(county = "Baltimore City", state = "MD", key = key)

balcity_annual_buyer <- combined_buyer_annual(county = "Baltimore City", state = "MD", key = key)

balcity_tract_data_working <- inner_join(balcity_annual_buyer, balcity_tract, by="BUYER_DEA_NO")

balcity_tract_data_working <- inner_join(balcity_tract_data_working, balcity_tract_income, by =c("GEOID"))

balcity_tract_data_working <- clean_names(balcity_tract_data_working)


```

```{R}

# Remove unecessary columns.

balcity_tract_data_working <-
  subset(balcity_tract_data_working, select = c(buyer_dea_no, buyer_county_x, buyer_state_x, year, dosage_unit, affgeoid, geoid, tractce, name_x, lsad, variable, estimate, moe, geometry))


```

```{r}

# Load full pipeline data for Baltimore City and Baltimore County. Unsure if it's necessary, but it's here now.

baltimore_city <- read_tsv("data/arcos-md-baltimore-city-24510-itemized.tsv")
baltimore_county <- read_tsv("data/arcos-md-baltimore-24005-itemized.tsv")


```

```{r}

# Clean up all the data that we just loaded (the data that I'm not sure is even necessary).

baltimore_city <- clean_names(baltimore_city)
baltimore_county <- clean_names(baltimore_county)

#pharmacy = buyer, manufacturer = labeler/company

baltimore_city_working <- baltimore_city %>%
  rename(manufacturer_name = combined_labeler_name)

baltimore_county_working <- baltimore_county %>%
  rename(manufacturer_name = combined_labeler_name)

#spaces between some columns and commas between others

baltimore_city_working <- baltimore_city %>%
  select(contains("buyer")) %>%
 unite(buyer_address_complete, buyer_address1, buyer_city, buyer_state, buyer_zip, remove = 'F', sep=" ") 

#I'm putting a space between some columns and a comma between others. 

baltimore_city_working <- baltimore_city %>%
  mutate(buyer_address_complete = paste0(buyer_address1," ", buyer_city, ", ", buyer_state, " ", buyer_zip)) 

#spaces between some columns and commas between others


baltimore_county_working <- baltimore_county %>%
  select(contains("buyer")) %>%
  unite(buyer_address_complete, buyer_address1, buyer_city, buyer_state, buyer_zip, remove = 'F', sep=" ") 

#I'm putting a space between some columns and a comma between others. 

baltimore_county_working <- baltimore_county %>%
  mutate(buyer_address_complete = paste0(buyer_address1," ", buyer_city, ", ", buyer_state, " ", buyer_zip))    

```

```{r}

balco_tract_data_working_2008 <- balco_tract_data_working %>%
  filter(year=="2008")

```

```{r}

# All right, starting off, I want to examine the highs and lows, comparing the city and the county, to get a sense of the data sets we'll be working with. My end goal is to examine how Baltimore County and City data compares to the national trends by income, race and opioid use. I've heard 2008 was the peak of the crisis, so I'm going to start by exploring some possible trends there.

#Question 1

#How large were the biggest shipments for Baltimore County in 2008?

balco_tract_data_working_2008 <- balco_tract_data_working_2008 %>%
  mutate(pills_category = case_when(
         dosage_unit > 10000 ~ "big shipment",
         dosage_unit < 5000 ~ "midsize shipment",
         TRUE ~ "small shipment"))

#1,914,740 is the highest result, followed by 1,160,400 and 801,400. Okay, that seems pretty high. I wonder how it compares to Baltimore City. 

```

```{r}

#Question 2

#For Baltimore County: Where did those highest pill counts go in 2008?

view(balco_tract_data_working)
  
#The first tract is 420100, the second is 451200 and the third is 492200. I don't have a great idea of where this is yet, but that'll be easy enough to figure out later on.
  
```

```{r}

#Question 3

#All right, so that comparison. How large were the biggest shipments for Baltimore City in 2008?

balcity_tract_data_working_2008 <- balcity_tract_data_working %>%
  filter(year=="2008")

#balcity_tract_data_working_2008 <- balcity_tract_data_working_2008
        #mutate(pills_category = case_when(
          #dosage_unit > 10000 ~ "big shipment",
          #dosage_unit < 5000 ~ "midsize shipment",
          #TRUE ~ "small shipment"))

#The biggest shipments were for 788,400, 467,840 and 445,600 pills. So, lower than Baltimore County's totals -- but why? Our analysis later on for income, race and opioid use will be helpful for trying to answer this.

# (Side note: It wouldn't let me knit unless I commented this part out, so I'm doing that for the time being.)

```


```{r}

#Question 4

#For Baltimore City in 2008: Where did they go?

view(balcity_tract_data_working_2008)

#They went to tracts 260402, 240300 and 271700. Again, we'll figure out location specifics a little later on.

```



```{r}

#Question 5

#To continue to get a better sense of the data: What are the annual pill totals per year for Baltimore County?


balco_yearly_pills <- summarized_county_annual(county="Baltimore", state="MD", key = key)

# In 2006 -- 21,894,869
# In 2007 -- 25,347,218
# In 2008 -- 27,664,210
# In 2009 -- 31,383,950
# In 2010 -- 34,224,000
# In 2011 -- 36,536,397
# In 2012 -- 35,372,927

#All right, that's a pretty steep increase.


```


```{r}

#Question 6

#What are the annual pill totals per year for Baltimore City?


balcity_yearly_pills <- summarized_county_annual(county="Baltimore City", state="MD", key = key)

#In 2006 -- 21,249,353
#In 2007 -- 16,362,494
#In 2008 -- 17,359,135
#In 2009 -- 18,172,455
#In 2010 -- 19,642,120
#In 2011 -- 20,262,816
#In 2012 -- 20,673,130


#...and Baltimore City's data is not that steep of an increase. Interesting.


```

``` {r}

#Question 7

#Which data tracts have the highest and lowest incomes in Baltimore County?

view(balco_tract_income)

#The highest incomes were in the high hundreds of thousands -- 198158, 167069 and 158908 -- while the lows were all below 40K (11190, 26402 and 35022).

# Later, I want to identify how this correlates to opioid use. Does our assumption that richer people have greater opioid use hold true in Baltimore County?


```


``` {r}

#Question 8

#Which data tracts have the highest and lowest incomes in Baltimore City?

view(balcity_tract_income)

#The highest incomes were also in the high hundreds of thousands -- 209167, 145966 and 	137275 -- while the lows were all below 15K (14452, 14520 and 14707).

#Wondering about the relationship here as well -- do higher incomes = higher opioid use in Baltimore City?

```


```{r}

#Question 9

#What's the pills per person breakdown in Baltimore County in 2008?

balco_2008_pills_per_person <- arcos_county_pills_per_year %>%
  filter(year=="2008") %>%
  inner_join(arcos_county_population_per_year, by=c("countyfips","year")) %>%
  mutate(pills_per_person = (dosage_unit/population))

balco_2008_pills_per_person <- balco_2008_pills_per_person %>%
  filter(buyer_county.x=="BALTIMORE")
  
#The average pills per person in Baltimore County in 2008 is 34.63867 pills.

#I don't have a great sense of how much this is until I find what Baltimore City has, and compare across years.


```


```{r}

#Question  10

#What's the pills per person breakdown in Baltimore City in 2008?

balcity_2008_pills_per_person <- arcos_county_pills_per_year %>%
  filter(year=="2008") %>%
  inner_join(arcos_county_population_per_year, by=c("countyfips","year")) %>%
  mutate(pills_per_person = (dosage_unit/population))

balcity_2008_pills_per_person <- balcity_2008_pills_per_person %>%
  filter(buyer_county.x=="BALTIMORE CITY")

#The average pills per person in Baltimore City in 2008 is 27.9903 pills. Hm, that's a bit lower. Let's see how they compare over time, because the disparity seems a little odd if they used to be close in number.


```

```{r}

#Question 11

#What does that look like over the course of multiple years, though? Let's take off the year filter. For Baltimore County:

balco_pills_per_person <- arcos_county_pills_per_year %>%
  inner_join(arcos_county_population_per_year, by=c("countyfips","year")) %>%
  mutate(pills_per_person = (dosage_unit/population))

balco_pills_per_person <- balco_pills_per_person %>%
  filter(buyer_county.x=="BALTIMORE")

#2006 -- 27.58468 pills per person
#2007 -- 31.84032 pills per person
#2008 -- 34.63867 pills per person
#2009 -- 39.89331 pills per person
#2010 -- 42.82309 pills per person
#2011 -- 45.52896 pills per person
#2012 -- 43.81536 pills per person

#Here, the low is in 2006, and then it continued to rise through 2012. Okay, now let's look at city data.



```

```{r}

#Question 12

#Same question, but for Baltimore City:


balcity_pills_per_person <- arcos_county_pills_per_year %>%
  inner_join(arcos_county_population_per_year, by=c("countyfips","year")) %>%
  mutate(pills_per_person = (dosage_unit/population))

balcity_pills_per_person <- balcity_pills_per_person %>%
  filter(buyer_county.x=="BALTIMORE CITY")

#2006 -- 34.21195 pills per person
#2007 -- 26.37810 pills per person
#2008 -- 27.99030 pills per person
#2009 -- 28.42391 pills per person
#2010 -- 31.65337 pills per person
#2011 -- 32.67090 pills per person
#2012 -- 33.30916 pills per person

#So opioids per person spiked in 2006 here, then decreased, and then stabilized, not increasing much more. Weird. 


```

```{r}

#Question 13

#Can we make a ggplot to visualize the Baltimore County data a little better? Let's see.

  ggplot(balco_pills_per_person) +
  geom_bar(stat="identity", aes(year, pills_per_person), fill="royal blue") +
  labs(x="Year", y="Total pills", title="Pills steadily raise, peak in 2011 for Baltimore County", subtitle = "Total pills shipped to Baltimore County by year", caption = "Source: DEA ARCOS database, via Washington Post") +
  scale_x_continuous(breaks = c(2006, 2007, 2008, 2009, 2010, 2011, 2012)) +
  scale_y_continuous()

#Yep. Pills peaked in 2011, but you can see a little more clearly how the shipments raised over time leading up to it.

```

```{r}

#Question 14

#What about Baltimore City? What sort of trends can we visualize with a ggplot?

  ggplot(balcity_pills_per_person) +
  geom_bar(stat="identity", aes(year, pills_per_person), fill="royal blue") +
  labs(x="Year", y="Total pills", title="Pills highest in Baltimore City during 2006, then dip before stabilizing", subtitle = "Total pills shipped to Baltimore County by year", caption = "Source: DEA ARCOS database, via Washington Post") +
  scale_x_continuous(breaks = c(2006, 2007, 2008, 2009, 2010, 2011, 2012)) +
  scale_y_continuous()

#No crazy findings from that, but it does help to see how drastic those changes are, given that we're dealing with some pretty large numbers for both data sets. 

```

```{r}

#Question 15

#What sort of trends do we notice when the data is grouped together visually?

#First, let's make a statewide set so Baltimore City and County data are together.

arcos_county_pills_per_year <- summarized_county_annual(key = key) %>%
  clean_names()

maryland_pills_per_year <- arcos_county_pills_per_year %>%
  filter(buyer_state == "MD", (buyer_county %in% c("BALTIMORE CITY", "BALTIMORE"))) %>%
  select(buyer_county, year, dosage_unit)


  ggplot(maryland_pills_per_year) +
  geom_bar(stat="identity", aes(year, dosage_unit, fill=buyer_county)) +
  labs(x="Year", y="Total pills", title="Opioids see more dramatic rise in Baltimore County than Baltimore City", subtitle = "Total pills per year shipped to Baltimore County and Baltimore City", caption = "Source: DEA ARCOS database, via Washington Post", fill="County") +
  scale_x_continuous(breaks = c(2006, 2007, 2008, 2009, 2010, 2011, 2012)) +
  facet_wrap(nrow=2, . ~ buyer_county) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  guides(fill="none")
  
  #Baltimore County appears to be almost double 2009 totals for the city. The increase over time in the county is more apparent than in the city. Still, the number of opioids seems noteworthy in both areas. 
  
  #This provides a pretty good foundation for our next steps -- comparing to national trends, and identifying which factors may be correlated with these changes. That's all for now, but I'm excited to see what's behind these differences. 


```


```{r}

#Question 16

#All right, time to get to the fun stuff

#Let's join median household income data and 

BalCo_income_by_tract <- get_acs(geography = "tract", state="MD", county="Baltimore",
             variables = "B19019_001", geometry = TRUE)
BalCo_tract <- pharm_tracts(county = "Baltimore", state = "MD", key = key)
moco_annual_buyer <- combined_buyer_annual(county = "Baltimore", state = "MD", key = key)
BalCo_income_by_tract <- inner_join(BalCo_annual_buyer, moco_tract, by="BUYER_DEA_NO")
BalCo_income_by_tract <- inner_join(BalCo_income_by_tract, , by = "GEOID")





```




















